### ISSUE TITLE
VU data not helpful

### ISSUE THREAD

**Issue by bassguitarbill** [ChrisMondok/Great-Adventure#2]
The VU data on this particular album might not e terribly useful. Overall, the percussion adds too much noise to make the data useful. Getting VU data for just the melody track won't work either, the notes don't often change in volume. Might need another approach, or scrap the VU idea.

**Comment by ChrisMondok** [comment]
I would think that the VU data would be purely for cosmetic / effects purposes, and not for any game logic.

**Comment by bassguitarbill** [comment]
Is "issues are appearing in my feed and I don't want them there" a valid reason to close an issue?
